CREATE DATABASE webcourses

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL,
  "email" varchar(30),
  "password" varchar(20) NOT NULL,
  "age" smallint,
  "rol_id" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(20) NOT NULL,
  "description" varchar(50),
  "level_id" int,
  "categories_id" int NOT NULL,
  "teacher_id" int NOT NULL
);

CREATE TABLE "courses_videos" (
  "id_courses" int,
  "url" varchar(40)
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30)
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rol" varchar(10) NOT NULL
);

CREATE TABLE "pivote_courses_users" (
  "users_id" int NOT NULL,
  "courses_id" int NOT NULL
);

CREATE TABLE "levels" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "level" varchar(10)
);

ALTER TABLE "users" ADD FOREIGN KEY ("rol_id") REFERENCES "roles" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("teacher_id") REFERENCES "users" ("id");

ALTER TABLE "pivote_courses_users" ADD FOREIGN KEY ("users_id") REFERENCES "users" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("categories_id") REFERENCES "categories" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("level_id") REFERENCES "levels" ("id");

ALTER TABLE "courses_videos" ADD FOREIGN KEY ("id_courses") REFERENCES "courses" ("id");

ALTER TABLE "pivote_courses_users" ADD FOREIGN KEY ("courses_id") REFERENCES "courses" ("id");


INSERT INTO levels (level) VALUES ('lo'), ('mid'), ('hi');

INSERT INTO roles (rol) VALUES ('student'), ('teacher'), ('admin');

INSERT INTO categories (name) VALUES ('chocolate'), ('meat'), ('vegan'), ('soup'), ('cookies');

INSERT INTO users (name, email, password, age, rol_id) VALUES ('kevin','kevin@gmail.com', 'abc', 10, 1), ('daniel', 'daniel@gmail.com', '123', 20, 3), ('nichu','nichu@gmail.com', '321', 30, 3), ('jerry','jerry@gmail.com', '321', 30, 2);





INSERT INTO courses (title, description, level_id, categories_id, teacher_id) VALUES ('cocina postres', 'aprende reposteria desde cero', 3, 3,2),  ('cocina entradas', 'aprende entradas y acompañamientos', 1, 4,1), ('platos fuertes', 'realiza los mejores platos del mundo', 2, 2,2);

INSERT INTO courses_videos (url) VALUES ('www.cocinando.com'), ('www.cocinando.com'), ('www.cocinando.com');



INSERT INTO pivote_courses_users (users_id, courses_id) VALUES (1,1),(1,2),(2,1),(2,2),(2,3),(3,1);

